version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@0.1.4
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - wget https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run Feature
#          command: bundle exec cucumber features/CheeseMachineFeature.feature
          command: rake default