version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@0.1.4
jobs:
  build:
    working_directory: /tmp/tests
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: create sharted folder
          command: |
            mkdir output
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run Feature
#          command: bundle exec cucumber features/CheeseMachineFeature.feature
          command: |
            rake ui_tests
            dir
      - run:
          name: copy output artifacts to shared folder
          command: |
            echo "### Original files in OUTPUT folder"
            ls output/

            echo "### Copy artifacts to shared folder:"
            cp -R output/. /tmp/tests/shared_folder
            ls /tmp/tests/shared_folder
#      - persist_to_workspace:
#          root: /tmp/tests
#          paths:
#            - shared_folder
      - store_artifacts:
          path: output
      - store_test_results:
          path: output