version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Run File
          command: ruby test.rb
      - run:
          name: Which bundler?
          command: bundle -v
            - ruby/bundle-install
            - cucumber "/features/test.feature" --format Teamcity::Cucumber::Formatter --expand --name "^Using the cheese machine$" --color -r features
