version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@0.1.4
jobs:
  build:
    working_directory: /tmp/tests
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run Feature
#          command: bundle exec cucumber features/CheeseMachineFeature.feature
          command: |
            rake ui_tests
            mkdir output
            dir
      - store_artifacts:
          path: /usr/local/bin/ruby/cucumberReport.html
      - store_test_results:
          path: /usr/local/bin/ruby/cucumberReport.html